// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
/// <reference types="node" />
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'src/infrastructure/persistence/prisma/schema.prisma',
  migrations: {
    path: 'src/infrastructure/persistence/prisma/migrations',
    seed: 'npx tsx src/infrastructure/persistence/prisma/seed.ts',
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
